// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace ProyectoFinal5.iOS
{
	public partial class CustomTextField : UITextField
	{
		public CustomTextField (IntPtr handle) : base (handle)
		{
            configurarPropiedades();
		}

        private void configurarPropiedades()
        {
            BorderStyle = UITextBorderStyle.None;
            Layer.BorderColor = UIColor.Gray.CGColor;
            Layer.BorderWidth = 0.5f;
            Layer.CornerRadius = 10f;

            Font = UIFont.FromName("Arial", 18f);
        }

        public override CGRect TextRect(CGRect forBounds)
        {
            var padding = new UIEdgeInsets(0, 10, 0, 0);

            return base.TextRect(padding.InsetRect(forBounds));
        }

        public override CGRect EditingRect(CGRect forBounds)
        {
            return TextRect(forBounds);
        }
	}
}
