// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using ProyectoFinal5.iOS.DAL.Services;
using ProyectoFinal5.Modelos.Entidades;
using UIKit;

namespace ProyectoFinal5.iOS
{
	public partial class DetalleViewController : UIViewController
	{
        UIAlertController _alerta;
        DetalleViaje _detalle;

		public DetalleViewController (IntPtr handle) : base (handle)
		{
		}

		public override async void ViewDidLoad()
		{
            base.ViewDidLoad();

            await ObtenerViajes();

            _detalle = TabsViewController.DetalleViaje.Detalle;

            TxtFechaInicial.Text = _detalle.FechaInicio.ToString();
            TxtFechaFinal.Text = _detalle.FechaFin.ToString();
            TxtKilometrajeInicial.Text = _detalle.KilometrajeInicial.ToString();
            TxtKilometrajeFinal.Text = _detalle.KilometrajeFinal.ToString();
            TxtObservaciones.Text = _detalle.Observaciones.ToString();
		}

        async Task<bool> ObtenerViajes()
        {
            var respuesta = await ClienteViajes.ObtenerDetalleViajeAsync(TabsViewController.ViajeId);

            if (!respuesta.TieneError)
            {
                TabsViewController.DetalleViaje = respuesta.Datos;
                return true;
            }
            else
            {
                MostrarMensaje("Error", respuesta.Mensaje);
                return false;
            }
        }

        void MostrarMensaje(string titulo, string mensaje)
        {
            _alerta = UIAlertController.Create(titulo, mensaje, UIAlertControllerStyle.Alert);
            _alerta.AddAction(UIAlertAction.Create("Aceptar", UIAlertActionStyle.Default, null));

            PresentViewController(_alerta, true, null);
        }
	}
}
