// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using ProyectoFinal5.iOS.Support;
using UIKit;

namespace ProyectoFinal5.iOS
{
    public partial class PrimaryButton : UIButton
    {
        public PrimaryButton(IntPtr handle) : base(handle)
        {
            Layer.CornerRadius = 10f;
            Layer.BackgroundColor = Colores.Primary.CGColor;
            Layer.BorderColor = Colores.DarkPrimary.CGColor;

            SetTitleColor(UIColor.White, UIControlState.Normal);

            Font = UIFont.FromName("Arial", 18f);

            TitleLabel.AdjustsFontSizeToFitWidth = true;
            TitleLabel.MinimumScaleFactor = 0.5f;

            Layer.ShadowColor = UIColor.Black.CGColor;
            Layer.ShadowOffset = new System.Drawing.SizeF(0f, 3f);
            Layer.ShadowRadius = 10f;
            Layer.ShadowOpacity = 0.4f;
        }
    }
}
